### ISSUE TITLE
Allow us to provide custom props on findAllAndFilterBySimpleProperties

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/cdav-library#109]
After https://github.com/nextcloud/server/pull/14389
I need to be able to request the `[NS.NEXTCLOUD, 'has-photo']` prop :)

https://github.com/nextcloud/cdav-library/blob/27c01a47aa007291976a2f8fa861cef8fc6fa075/src/models/addressBook.js#L83-L102

@georgehrke

**Comment by georgehrke** [comment]
@skjnldsv Feel free to simply add `[NS.NEXTCLOUD, 'has-photo']` to `
return this.addressbookQuery(null, [...` :) 

`findAllAndFilterBySimpleProperties` is a very contacts app specific method anyway.
