### ISSUE TITLE
[Enhancement] Documentation on use would be wonderfully useful

### ISSUE THREAD

**Issue by SLYtiger16** [nextcloud/cdav-library#304]

**Comment by georgehrke** [comment]
Please see https://github.com/nextcloud/cdav-library/issues/36 and https://github.com/nextcloud/cdav-library/issues/77.

**Comment by SLYtiger16** [comment]
@georgehrke I actually ended up implementing my own JS/Node solution which I documented thoroughly and published to npm ... 
https://github.com/SLYtiger16/caldavjs-nextcloud 
I hope this is helpful to those who land here looking for an external API with documentation as well as at #77 and #36

**Comment by tx0h** [comment]
> No description provided.

yes, still looking for some basic examples. for cardav and caldav. the code from the issuer isn't available anymore. please, find some time and add basic client skeletons and a simple reference manual. would be helpful.
