### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/cdav-library#336]
```
dist.js:formatted:1 TypeError: Cannot read property 'length' of undefined
    at dist.js:formatted:1
    at Array.forEach (<anonymous>)
    at e.value (dist.js:formatted:1)
    at e.<anonymous> (dist.js:formatted:1)
    at c (dist.js:formatted:1)
    at Generator._invoke (dist.js:formatted:1)
    at Generator.forEach.t.<computed> [as next] (dist.js:formatted:1)
    at Ot (dist.js:formatted:1)
    at a (dist.js:formatted:1)
```

https://github.com/nextcloud/cdav-library/blob/4d9919a3d1c1d1931203e715f6a404f73e3151d8/src/models/davCollection.js#L349

Got this when uploading some vcf to a customer instance.
Not sure why, only happened 3 times over a 200+ list of contacts :shrug:

**Comment by wilbowma** [comment]
I think this line:
```
			if (props['{DAV:}resourcetype'].length === 0) {
```

Needs to be changed to:
```
			if (!props['{DAV:}resourcetype'] || (props['{DAV:}resourcetype'].length === 0)) {
```

At least in the Radicale CalDAV server, VTODOs don't have a `resourcetype`, so it's undefined when returned from the server. This seems to be consistent with the CalDAV spec as far as I can tell.

Doing this fixed this issue: https://github.com/johannesjo/super-productivity/issues/1192

**Comment by tcitworld** [comment]
> This seems to be consistent with the CalDAV spec as far as I can tell.

Can you point out why? CalDAV doesn't seem to say anything about this, and the DAV RFCs say
> The resourcetype property MUST be defined on all DAV compliant resources. The default value is empty.

**Comment by wilbowma** [comment]
I tested the following file using https://icalendar.org/validator.html

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//Apple Inc.//iOS 14.5.1//EN
BEGIN:VTODO
CLASS:PRIVATE
CREATED:20190604T070127Z
DTSTAMP:20210508T084425Z
LAST-MODIFIED:20210507T174058Z
SEQUENCE:4
STATUS:NEEDS-ACTION
SUMMARY:Use example in blog post
UID:E7CE2FA9-FD0D-4888-B5C7-7693C8B2C607
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Reminder
TRIGGER;VALUE=DATE-TIME:20190906T190000Z
UID:29640889-4D8C-467B-9311-4CCAC25A1DEF
X-KDE-KCALCORE-ENABLED:TRUE
X-WR-ALARMUID:29640889-4D8C-467B-9311-4CCAC25A1DEF
END:VALARM
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Reminder
TRIGGER;VALUE=DATE-TIME:20190813T190000Z
UID:821DEC02-B2EA-410A-AEB9-E95AF2083BDF
X-KDE-KCALCORE-ENABLED:TRUE
X-WR-ALARMUID:821DEC02-B2EA-410A-AEB9-E95AF2083BDF
END:VALARM
X-APPLE-SORT-ORDER:1
END:VTODO
END:VCALENDAR
```

It passed. While reading the RFCs, I could only find references to `resourcetype` being required regarding collections. Could you link to the RFC you're referencing?

**Comment by wilbowma** [comment]
I found https://datatracker.ietf.org/doc/html/rfc2518#section-13.9

I think I'm getting the iCal object format and the DAV specification confused.

**Comment by wilbowma** [comment]
OTOH, the CalDAV RFC shows examples without a resourcetype:
https://datatracker.ietf.org/doc/html/rfc4791#section-7.8.5
