### ISSUE TITLE
Requirements for CardDAV

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/cdav-library#4]
Hey @Henni @skjnldsv 

One thing you can do before we get started in a couple of weeks would be documenting requirements for the CardDAV library. 

Stuff like:
- [ ] queries with limit/offset (lazy loading)
- [ ] load contacts by groups
- [ ] "group statistics" (you probably need some way to get a list of all groups / the number of contacts per group without loading all contacts first)
- [ ] etc.
- [x] filter out unwanted properties of vcards/ical

Do you need some kind of search API for filter all contacts by their properties?

**Comment by georgehrke** [comment]
@raimund-schluessler The same goes for you :)
If you have any special requirements for querying Todos from the server, just let me know and we will provide a method for that in this library

**Comment by skjnldsv** [comment]
@georgehrke for now, we just filter our properties with dav (we implemented the update into the 3rdparty a while ago iirc). So basically, we're requesting vcards with only the name, groups, uid and rev. and we preload all the contacts shown in the contacts list with full pictures (after the initial short load).
But we only request the full vcard on load.
