### ISSUE TITLE
Versioning and publishing

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/cdav-library#400]
I read in https://github.com/nextcloud/cdav-library/issues/325 that the lib was not put on the npm registry deliberately. However, I now also see that when it's used in apps you don't have any versioning (except from commits) and therefore it's a bit hard to keep book about what version is used in which app/release, especially when it comes to backports.

Therefore I think publishing still makes sense. The app can be namespaced with `@nextcloud/` like the other packages and we can make it clear that this package is for internals of Nextcloud and no general purpose webdav lib.

@juliushaertl @skjnldsv @tcitworld objections?

**Comment by tcitworld** [comment]
We could also use simple git tags to handle versioning instead of commits, but publishing under the `@nextcloud` namespace seems fine to me.

**Comment by ChristophWurst** [comment]
What I dislike about using git references is that you have to check in your build artifacts. With npm releases the build happens only during release and not for every ever so tiny commit.

**Comment by skjnldsv** [comment]
Agree on the git reference.
Let's move this to npm, we've been using this lib for over 2 years now

**Comment by tcitworld** [comment]
Avoiding things like https://github.com/nextcloud/cdav-library/pull/498 :)
