### ISSUE TITLE
Installing this via npm broken by one of the newer commits

### ISSUE THREAD

**Issue by johannesjo** [nextcloud/cdav-library#609]
I'm installing this lib via npm like so:
```
npm i git+https://github.com/nextcloud/cdav-library.git
```

Which won't properly install anything, just an empty directory apart from the package.json.

Fixed by executing:
```
npm i git+https://github.com/nextcloud/cdav-library.git#d8cdc23df38b10641f52ec97fd2daa86080cfe1d
```

**Comment by tcitworld** [comment]
You need to directly use the published package on npm now : https://www.npmjs.com/package/@nextcloud/cdav-library

**Comment by johannesjo** [comment]
Didn't know there is one. Thank you!!
