### ISSUE TITLE
Conflict handling is broken

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/cdav-library#65]
Hey @georgehrke 
When I added the etag writing thing, I made sure that in case of conflict, the contact was set to being partial (since data was missing and/or changed) https://github.com/nextcloud/cdav-library/blob/514f0674b72eb486d25a2ab392c20c2b2e7f1fdb/src/models/davObject.js#L126-L129

But this is not the case anymore and is therefore breaking the contacts behavior since forcing a fullfetch will return undefined instead of updating the vcard data.
https://github.com/nextcloud/cdav-library/blob/f8d2318e4c7bcda196e8bb8fc508c46747744f05/src/models/davObject.js#L138-L151

What shall we do here?
Shall I manually set the contact to partial?
I feel like this should be built-in :thinking:

**Comment by georgehrke** [comment]
> What shall we do here?
Shall I manually set the contact to partial?

Just catch, check for 412, reject again.

Will fix tonight
