### ISSUE TITLE
Where is the API? How do I use it?

### ISSUE THREAD

**Issue by elspru** [nextcloud/cdav-library#77]
Hi, 

I'm hoping there can be an API or something to allow people to use this library. 

In particular I would like a complete example of how to authenticate and get calendars and events, 
as well as how to set them.

I found a partial example in #36 
```
await client.connect({enableCalDAV: true});
const calendars = await client.calendarHomes[0].findAllCalDAVCollections()
const events = await calendars[0].findAllVObjects()
console.log(events[0].data);
```
but it seems incomplete, like where do I put the username and password or apiKey?
Also how would I set new events?

Examples of how to use the cardDav would be great also.

Thanks

**Comment by georgehrke** [comment]
I explained authentication in #36. If you don’t run your code as a Nextcloud app, you have to deal with authentication yourself in the xhrProvider. Just add a basic auth header.

Events you can add by calling “createVObject” on a calendar object. To get a complete API documentation, just run `npm run build-doc`

**Comment by georgehrke** [comment]
```
function xhrProvider() {
	var headers = {
		'X-Requested-With': 'XMLHttpRequest',
		'requesttoken': OC.requestToken
	}
	var xhr = new XMLHttpRequest()
	var oldOpen = xhr.open

	// override open() method to add headers
	xhr.open = function() {
		var result = oldOpen.apply(this, arguments)
		for (let name in headers) {
			xhr.setRequestHeader(name, headers[name])
			xhr.setRequestHeader('Authorization', 'Basic ' + btoa(unescape(encodeURIComponent(YOUR_USERNAME + ':' + YOUR_PASSWORD))))
		}
		return result
	}
	OC.registerXHRForErrorProcessing(xhr)
	return xhr
}

const client = new DavClient({
	rootUrl: OC.linkToRemote('dav')
}, xhrProvider)

await client.connect({enableCalDAV: true});
const calendars = await client.calendarHomes[0].findAllCalDAVCollections()
const events = await calendars[0].findAllVObjects()
console.log(events[0].data);
```

You can read more about Http auth here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#The_general_HTTP_authentication_framework

The URL of the server is given in `rootUrl: OC.linkToRemote('dav')`. You have to replace that with your URL. Just point it to `/remote.php/dav/` of your Nextcloud instance.

**Comment by georgehrke** [comment]
@elspru Did that answer your question? :)

**Comment by elspru** [comment]
Hi @georgehrke it does seem to be better, but I'm still not really sure how to use it.
Like I'm trying to use this for a node application, but it seems that the code you gave me is for a web browser, and I'm not sure how to require() stuff in it. like should I have a sample web page also or something?

 Maybe If I explain my use case it will make more sense. 
I want to have a chat bot that can send me calendar notifications, and have event specific behaviour. Like if I'm hosting a meditation session, it can read the title to know that, and then it will ask me at the appropriate times stuff like "what is the head count?" and "how much was donated?",  so that the bot can function as my secretary and put that into the csv files and generate the website accordingly so the community knows where we are at, and if we have enough donations to cover the year more or less in real time.

**Comment by elspru** [comment]
I tried this:

```
<script src=cdav-library.js></script>                                            
  <script>                                                                       
    function xhrProvider() {                                                     
        var headers = {                                                          
                'X-Requested-With': 'XMLHttpRequest',                            
                'requesttoken': OC.requestToken                                  
        }                                                                        
        var xhr = new XMLHttpRequest()                                           
        var oldOpen = xhr.open                                                   
                                                                                 
        // override open() method to add headers                                 
        xhr.open = function() {                                                  
                var result = oldOpen.apply(this, arguments)                      
                for (let name in headers) {                                      
                        xhr.setRequestHeader(name, headers[name])                
                        xhr.setRequestHeader('Authorization', 'Basic ' +         
                          btoa(unescape(encodeURIComponent('logan' + ':' + 'F8i8gSDeNDmZdBCr8p'))))
                }                                                                
                return result                                                    
        }                                                                        
        OC.registerXHRForErrorProcessing(xhr)                                    
        return xhr                                                               
}                                                                                
                                                                                 
const client = new DavClient({                                                   
  rootUrl: 'https://nc.liberit.ca', // OC.linkToRemote('dav')                    
}, xhrProvider)                                                                  
                                                                                 
async function init(){                                                           
await client.connect({enableCalDAV: true});                                      
const calendars = await client.calendarHomes[0].findAllCalDAVCollections()       
const events = await calendars[0].findAllVObjects()                              
console.log(events[0].data);                                                     
console.log('hello world');                                                      
}                                                                                
  </script>                                                                      
<body onload="init()">                                                           
  hello                                                                          
</body>
```

It tells me DavClient

**Comment by Mordef** [comment]
Same here, no DavClient defined. There is 'cdav' but:
TypeError: cdav is not a constructor

**Comment by georgehrke** [comment]
I'm not sure if it will work when using `<script src=cdav-library.js></script>`, because we use `ES6 Modules`. 

Please see https://hacks.mozilla.org/2015/08/es6-in-depth-modules/ how to use them.
But i would recommend to use web pack in the meantime, until all major browsers adapted `ES6 Modules`.

An example how to use this library with web pack can be found in the contacts app.

**Comment by georgehrke** [comment]
Since there was no response or no further questions here for two months i will close this ticket.
